version: '3.8'
networks:
  monitoring:
    driver: bridge
volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
services:
  prometheus:
    image: prom/prometheus:v2.37.9
    container_name: prometheus
    ports:
      - 1783:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    volumes:
      - ./config/:/etc/prometheus/
      - ./data:/prometheus/data/
    restart: unless-stopped
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081
    restart: unless-stopped
  asciidoctor:
    image: asciidoctor/docker-asciidoctor
    container_name: asciidoctor
    ports:
      - "8815:8815"
    hostname: asciidoctor
    volumes:
      - ./reportgen:/documents
    command:
      sh /documents/startup.sh
    restart: unless-stopped
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alert:/etc/alertmanager
    restart: unless-stopped
  yace:
    build:
      context: ./yet-another-cloudwatch-exporter
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      AWS_REGION: ap-south-1
      AWS_ACCESS_KEY_ID: 
      AWS_SECRET_ACCESS_KEY: 
    expose:
      - 8099
    volumes:
      - ./yace/yace-config.yaml:/tmp/config.yml
    command:
      - -listen-address=:8099
      - -config.file=/tmp/config.yml`
  blackbox_exporter:
    image: quay.io/prometheus/blackbox-exporter:latest
    ports:
      - "9115:9115"
    restart: unless-stopped
    volumes:
      - ./blackbox/blackbox.yaml:/config/blackbox.yaml
    command:
      - "--config.file=/config/blackbox.yaml"
